services:
  frontend:
    build: /frontend
    ports:
      - "5173:5173"
    networks:
      - mern_network
    environment:
      - BASE_URL=http://backend:3000

  backend:
    build: /backend
    ports: -"3000:3000"
    environment:
      - MONGO_URI=mongodb+srv://divyakirantatikonda:wGqTqlkblWlXDWt3@namastenodejs.4letz.mongodb.net/devTinder
    networks:
      - mern_network
    depends_on:
      - frontend

  networks:
    mern: driver:bridge
